Add cli-ui gem dependency (#23)
The [Developer
CLI](https://github.com/Betterment/demo_mode?tab=readme-ov-file#developer-cli)
uses [cli-ui](https://github.com/Shopify/cli-ui), but doesn't include it
as a dependency, thus requiring the vendoring app to depend on that gem
directly in order to leverage the CLI.

Running `bundle exec rails persona:create` from a project that doesn't
depend on `cli-ui` currently produces the following error:

```
NameError: uninitialized constant DemoMode::Clis::MultiWordSearchPatch::CLI (NameError)

      CLI::UI::Prompt.const_get(:InteractiveOptions)
             ^^^^^^^^
```