Handle case where table-filter is not found (#12)
When there are no standard personas, the
`input[data-behavior=table-filter]` element won't exist (see
[here](https://github.com/Betterment/demo_mode/blob/46f82a095c4cd283c93354d7734437d7b4aff3c5/app/views/demo_mode/sessions/new.html.erb#L21)).
As a result, the following JS error is thrown:
> TypeError: Cannot set properties of null (setting 'oninput')

This PR does an early return if that input is not found.

In addition to this bugfix, the following maintenance has been
performed:
* Bumped the version.
* Switch to Cuprite. It's simpler to configure and would have caught
this error with `js_errors: true`.
* Removed Ruby 2.7 from the build matrix.
* Removed Rails 6.0 from the build matrix.
* Added Ruby 3.2 to the build matrix.
* Fixed new Rubocop violations.